scrape_configs:
  - job_name: 'Cisco-Nexus'
    static_configs:
      - targets:
          - 192.168.110.1
    metrics_path: /snmp
    params:
      module: []
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116
